ALTER TABLE admin_settings
  ADD COLUMN IF NOT EXISTS location_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS location_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS location_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS location_radius_meters INT NOT NULL DEFAULT 200,
  ADD COLUMN IF NOT EXISTS location_name TEXT;
